[package]
name = "rust-fullstack-template-shared"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[dependencies]
bumpalo = { version = "3.6.1", features = ["collections"] }
lignin = { git = "https://github.com/Tamschi/lignin.git", branch = "develop" }
